[package]
name = "flood_monitor"
version = "0.1.0"
edition = "2024"


[dependencies]
env_logger = "0.11.8"
lazy_static = "1.5.0"
log = "0.4.29"
meshtastic = "0.1.8"
serde = "1.0.228"
serde_json = "1.0.148"
tokio = "1.48.0"
